//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLog
    {
        public int CallID { get; set; }
        public int StudentID { get; set; }
        public string UserID { get; set; }
        public int LanguageSpokenID { get; set; }
        public string LanguageSpokenOther { get; set; }
        public Nullable<System.DateTime> CallStart { get; set; }
        public Nullable<System.DateTime> CallEnd { get; set; }
        public bool ParentParticipation { get; set; }
        public bool CallDropped { get; set; }
        public bool CallTransferred { get; set; }
        public bool PostTestGiven { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string SkillAssessedNotes { get; set; }
        public string SessionEvalNotes { get; set; }
        public Nullable<int> EvalStartID { get; set; }
        public Nullable<int> EvalEndID { get; set; }
        public bool Textbook { get; set; }
        public bool Worksheet { get; set; }
        public bool Stoodle { get; set; }
        public bool ImageShare { get; set; }
        public bool Chat { get; set; }
        public Nullable<System.DateTime> PrizeGiven { get; set; }
        public Nullable<int> PrizeID { get; set; }
        public bool IsLocked { get; set; }
        public bool BeatMath { get; set; }
        public bool IsDeleted { get; set; }
        public string PrizeStudentName { get; set; }
        public string PrizeTeacherName { get; set; }
        public bool GoogleDocs { get; set; }
        public bool GoogelDocs { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Prize Prize { get; set; }
        public virtual Student Student { get; set; }
        public virtual EvalEnd EvalEnd { get; set; }
        public virtual EvalStart EvalStart { get; set; }
        public virtual LanguageType LanguageType { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
