//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorGiving
    {
        public int DonorGivingID { get; set; }
        public int DonorID { get; set; }
        public decimal AmountGiven { get; set; }
        public System.DateTime DateGiven { get; set; }
        public bool InKind { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Donor Donor { get; set; }
    }
}
