//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> SchoolTypeID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string Phone { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalEmail { get; set; }
        public Nullable<decimal> PEDS { get; set; }
        public Nullable<int> Census { get; set; }
        public Nullable<int> PredictedThirdGradeStudents { get; set; }
        public Nullable<int> SchoolBoardDistrict { get; set; }
        public Nullable<int> CityCouncilDistrict { get; set; }
        public Nullable<bool> SonicPartner { get; set; }
        public Nullable<bool> TitleOneSchool { get; set; }
        public Nullable<bool> AppalachianRegion { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> QuadrantID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FlashCardQty { get; set; }
        public string CreateBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual County County { get; set; }
        public virtual SchoolType SchoolType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual SchoolDistrict SchoolDistrict { get; set; }
        public virtual MnpsQuadrant MnpsQuadrant { get; set; }
    }
}
