//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        public int TimeEntryID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool IsLocked { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> PayrollDate { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
