//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PrincipalList
    {
        public string CountyName { get; set; }
        public string SchoolTypeName { get; set; }
        public string PrincipalName { get; set; }
        public Nullable<int> Census { get; set; }
        public string Phone { get; set; }
        public string SchoolName { get; set; }
        public int SchoolID { get; set; }
        public string PrincipalEmail { get; set; }
    }
}
